amr_identity: 90
amr_coverage: 90
assembly_depth: 2
assembly_min: 1000
custom_taxa: db/42_Bacterial_Phyla_2022.csv
db_kraken: /scratch1/databases/kraken/20210810_kraken2_standard/
bracken_min_reads: 10
kraken_confidence_score: 0.0
kraken_read_length: 150
metaquast_max_refs: 5